version: 2
jobs:
  test:
    docker:
      - image: python
    steps:
      - checkout
      - run:
          name: Install packages
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py install
            pip install -r test-requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest --cov-report html
      - store_artifacts:
          path: htmlcov
          destination: coverage
workflows:
  version: 2
  commit:
    jobs:
      - test
  nightly:
    jobs:
      - test
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
