version: 2
jobs:
  build:
    docker:
      - image: python
    steps:
      - checkout
      - run:
          name: Install packages
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py install
            pip install -r test-requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest --cov-report html
      - store_artifacts:
          path: htmlcov
          destination: coverage
